name: EnthusiaMarket
version: ${version}
api-version: '1.21'
load: STARTUP
main: net.badgersmc.em.EnthusiaMarket
depend: [LumaGuilds, WorldGuard, Vault]
softdepend: [floodgate, PlaceholderAPI]

commands:
  enthusiamarket:
    description: EnthusiaMarket administrative commands
    usage: /enthusiamarket <subcommand>
    aliases: [em]

permissions:
  enthusiamarket.*:
    default: op
    children:
      enthusiamarket.admin: true
      enthusiamarket.player: true
  enthusiamarket.admin:
    default: op
    children:
      enthusiamarket.admin.import: true
      enthusiamarket.admin.list: true
      enthusiamarket.admin.evict: true
      enthusiamarket.admin.reload: true
      enthusiamarket.admin.setowner: true
      enthusiamarket.admin.refund: true
      enthusiamarket.auction.cancel.force: true
  enthusiamarket.player:
    default: true
    children:
      enthusiamarket.stall.rent: true
      enthusiamarket.stall.bid: true
      enthusiamarket.stall.manage.own: true
      enthusiamarket.stall.manage.guild: true
      enthusiamarket.stall.favorite: true
      enthusiamarket.shop.create: true
      enthusiamarket.shop.break: true
      enthusiamarket.shop.buy: true
      enthusiamarket.shop.sell: true
      enthusiamarket.auction.start: true
      enthusiamarket.auction.bid: true
      enthusiamarket.auction.cancel: true
      enthusiamarket.auction.list: true
      enthusiamarket.bedrock.form: true
